apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: papers
  namespace: argo-cd
spec:
  project: default
  source:
    repoURL: https://github.com/unsw-cse-comp99-3900/capstone-project-25t3-3900-h09b-banana.git
    targetRevision: develop
    path: deployment/helm-chart
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: papers
